
const albums = [
    { id: 1, title: 'The Dark Side of the Moon', artist: 'Pink Floyd', year: 1973 },
    { id: 2, title: 'Abbey Road', artist: 'The Beatles', year: 1969 },
    { id: 3, title: 'Thriller', artist: 'Michael Jackson', year: 1982 },
    { id: 4, title: 'Back in Black', artist: 'AC/DC', year: 1980 },
    { id: 5, title: 'The Wall', artist: 'Pink Floyd', year: 1979 },
    { id: 6, title: 'Hotel California', artist: 'Eagles', year: 1976 },
    { id: 7, title: 'Led Zeppelin IV', artist: 'Led Zeppelin', year: 1971 },
    { id: 8, title: 'Rumours', artist: 'Fleetwood Mac', year: 1977 },
    { id: 9, title: 'Nevermind', artist: 'Nirvana', year: 1991 },
    { id: 10, title: 'Sgt. Pepper\'s Lonely Hearts Club Band', artist: 'The Beatles', year: 1967 },
    { id: 11, title: 'Born to Run', artist: 'Bruce Springsteen', year: 1975 },
    { id: 12, title: 'The Joshua Tree', artist: 'U2', year: 1987 },
    { id: 13, title: 'The Beatles (The White Album)', artist: 'The Beatles', year: 1968 },
    { id: 14, title: 'Pet Sounds', artist: 'The Beach Boys', year: 1966 },
    { id: 15, title: 'A Night at the Opera', artist: 'Queen', year: 1975 },
    { id: 16, title: 'Goodbye Yellow Brick Road', artist: 'Elton John', year: 1973 },
    { id: 17, title: 'Purple Rain', artist: 'Prince', year: 1984 },
    { id: 18, title: 'Hunky Dory', artist: 'David Bowie', year: 1971 },
    { id: 19, title: 'Tapestry', artist: 'Carole King', year: 1971 },
    { id: 20, title: 'Sticky Fingers', artist: 'The Rolling Stones', year: 1971 },
    { id: 21, title: 'Exile on Main St.', artist: 'The Rolling Stones', year: 1972 },
    { id: 22, title: 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', artist: 'David Bowie', year: 1972 },
    { id: 23, title: 'Who\'s Next', artist: 'The Who', year: 1971 },
    { id: 24, title: 'Darkness on the Edge of Town', artist: 'Bruce Springsteen', year: 1978 },
    { id: 25, title: 'Highway to Hell', artist: 'AC/DC', year: 1979 },
    { id: 26, title: 'In the Court of the Crimson King', artist: 'King Crimson', year: 1969 },
    { id: 27, title: 'Graceland', artist: 'Paul Simon', year: 1986 },
    { id: 28, title: 'Appetite for Destruction', artist: 'Guns N\' Roses', year: 1987 },
    { id: 29, title: 'London Calling', artist: 'The Clash', year: 1979 },
    { id: 30, title: 'Blonde on Blonde', artist: 'Bob Dylan', year: 1966 },
    { id: 31, title: 'The Doors', artist: 'The Doors', year: 1967 },
    { id: 32, title: 'Bridge Over Troubled Water', artist: 'Simon & Garfunkel', year: 1970 },
    { id: 33, title: 'Electric Ladyland', artist: 'The Jimi Hendrix Experience', year: 1968 },
    { id: 34, title: 'Innervisions', artist: 'Stevie Wonder', year: 1973 },
    { id: 35, title: 'The Velvet Underground & Nico', artist: 'The Velvet Underground', year: 1967 },
    { id: 36, title: 'OK Computer', artist: 'Radiohead', year: 1997 },
    { id: 37, title: 'Blue', artist: 'Joni Mitchell', year: 1971 },
    { id: 38, title: 'The Chronic', artist: 'Dr. Dre', year: 1992 },
    { id: 39, title: 'My Beautiful Dark Twisted Fantasy', artist: 'Kanye West', year: 2010 },
    { id: 40, title: 'Revolver', artist: 'The Beatles', year: 1966 },
    { id: 41, title: 'Master of Puppets', artist: 'Metallica', year: 1986 },
    { id: 42, title: 'The Miseducation of Lauryn Hill', artist: 'Lauryn Hill', year: 1998 },
    { id: 43, title: 'A Love Supreme', artist: 'John Coltrane', year: 1965 },
    { id: 44, title: 'Songs in the Key of Life', artist: 'Stevie Wonder', year: 1976 },
    { id: 45, title: 'Kind of Blue', artist: 'Miles Davis', year: 1959 },
    { id: 46, title: 'Blood on the Tracks', artist: 'Bob Dylan', year: 1975 },
    { id: 47, title: 'Low', artist: 'David Bowie', year: 1977 },
    { id: 48, title: 'The College Dropout', artist: 'Kanye West', year: 2004 },
    { id: 49, title: 'The Suburbs', artist: 'Arcade Fire', year: 2010 },
    { id: 50, title: 'Doolittle', artist: 'Pixies', year: 1989 },
    { id: 51, title: 'To Pimp a Butterfly', artist: 'Kendrick Lamar', year: 2015 },
    { id: 52, title: 'Illmatic', artist: 'Nas', year: 1994 },
    { id: 53, title: 'After the Gold Rush', artist: 'Neil Young', year: 1970 },
    { id: 54, title: 'Horses', artist: 'Patti Smith', year: 1975 },
    { id: 55, title: 'Are You Experienced', artist: 'The Jimi Hendrix Experience', year: 1967 },
    { id: 56, title: 'The Queen Is Dead', artist: 'The Smiths', year: 1986 },
    { id: 57, title: 'Disraeli Gears', artist: 'Cream', year: 1967 },
    { id: 58, title: 'The Bends', artist: 'Radiohead', year: 1995 },
    { id: 59, title: 'Let It Bleed', artist: 'The Rolling Stones', year: 1969 },
    { id: 60, title: 'American Idiot', artist: 'Green Day', year: 2004 },
    { id: 61, title: 'Blonde', artist: 'Frank Ocean', year: 2016 },
    { id: 62, title: 'The Eminem Show', artist: 'Eminem', year: 2002 },
    { id: 63, title: 'Automatic for the People', artist: 'R.E.M.', year: 1992 },
    { id: 64, title: 'The Clash', artist: 'The Clash', year: 1977 },
    { id: 65, title: 'Born in the U.S.A.', artist: 'Bruce Springsteen', year: 1984 },
    { id: 66, title: 'Superfly', artist: 'Curtis Mayfield', year: 1972 },
    { id: 67, title: 'Legend', artist: 'Bob Marley and the Wailers', year: 1984 },
    { id: 68, title: 'Moving Pictures', artist: 'Rush', year: 1981 },
    { id: 69, title: 'Songs of Leonard Cohen', artist: 'Leonard Cohen', year: 1967 },
    { id: 70, title: 'The Stone Roses', artist: 'The Stone Roses', year: 1989 },
    { id: 71, title: 'Tango in the Night', artist: 'Fleetwood Mac', year: 1987 },
    { id: 72, title: 'Red', artist: 'Taylor Swift', year: 2012 },
    { id: 73, title: 'Beggars Banquet', artist: 'The Rolling Stones', year: 1968 },
    { id: 74, title: 'Good Kid, M.A.A.D City', artist: 'Kendrick Lamar', year: 2012 },
    { id: 75, title: 'Use Your Illusion I', artist: 'Guns N\' Roses', year: 1991 },
    { id: 76, title: 'Use Your Illusion II', artist: 'Guns N\' Roses', year: 1991 },
    { id: 77, title: 'AM', artist: 'Arctic Monkeys', year: 2013 },
    { id: 78, title: 'Paranoid', artist: 'Black Sabbath', year: 1970 },
    { id: 79, title: 'Maggot Brain', artist: 'Funkadelic', year: 1971 },
    { id: 80, title: 'Fear of Music', artist: 'Talking Heads', year: 1979 },
    { id: 81, title: '2112', artist: 'Rush', year: 1976 },
    { id: 82, title: 'Loveless', artist: 'My Bloody Valentine', year: 1991 },
    { id: 83, title: 'In the Aeroplane Over the Sea', artist: 'Neutral Milk Hotel', year: 1998 },
    { id: 84, title: 'Daydream Nation', artist: 'Sonic Youth', year: 1988 },
    { id: 85, title: 'Kid A', artist: 'Radiohead', year: 2000 },
    { id: 86, title: 'Physical Graffiti', artist: 'Led Zeppelin', year: 1975 },
    { id: 87, title: 'Ride the Lightning', artist: 'Metallica', year: 1984 },
    { id: 88, title: 'Blurryface', artist: 'Twenty One Pilots', year: 2015 },
    { id: 89, title: 'Bad', artist: 'Michael Jackson', year: 1987 },
    { id: 90, title: 'Lemonade', artist: 'Beyoncé', year: 2016 },
    { id: 91, title: 'Grace', artist: 'Jeff Buckley', year: 1994 },
    { id: 92, title: 'Demon Days', artist: 'Gorillaz', year: 2005 },
    { id: 93, title: 'Eliminator', artist: 'ZZ Top', year: 1983 },
    { id: 94, title: 'The Colour and the Shape', artist: 'Foo Fighters', year: 1997 },
    { id: 95, title: 'Is This It', artist: 'The Strokes', year: 2001 },
    { id: 96, title: 'Songs for the Deaf', artist: 'Queens of the Stone Age', year: 2002 },
    { id: 97, title: 'Reputation', artist: 'Taylor Swift', year: 2017 },
    { id: 98, title: 'Hot Fuss', artist: 'The Killers', year: 2004 },
    { id: 99, title: 'Ziggy Stardust', artist: 'David Bowie', year: 1972 },
    { id: 100, title: 'Rage Against the Machine', artist: 'Rage Against the Machine', year: 1992 }
];

export default albums;
